development:
  stripe_secret_key: 'sk_test_iKubRwNDxPRmYyzdtFQsSe8H00cPWw8aWJ'

  stripe_publishable_key: 'pk_test_TtsHts0jEzYIV2MAKFEoKIqY00yxkr42i5'


production:
  stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
  stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'